import {
  CalendarDays,
  FileText,
  HardDrive,
  Images,
  Mail,
  MessageSquare,
  CheckCircle2,
} from "lucide-react";

export const CONNECTORS = [
  {
    id: "google-calendar",
    composioSlug: "googlecalendar",
    name: "Google Calendar",
    detail: "Meetings and reminders",
    icon: CalendarDays,
    color: "text-blue-500",
    surface: "border-blue-500/20 bg-blue-500/5",
  },
  {
    id: "google-mail",
    composioSlug: "gmail",
    name: "Gmail",
    detail: "Important email context",
    icon: Mail,
    color: "text-red-500",
    surface: "border-red-500/20 bg-red-500/5",
  },
  {
    id: "google-photos",
    composioSlug: "googlephotos",
    name: "Google Photos",
    detail: "Photos and videos",
    icon: Images,
    color: "text-emerald-500",
    surface: "border-emerald-500/20 bg-emerald-500/5",
  },
  {
    id: "google-drive",
    composioSlug: "googledrive",
    name: "Google Drive",
    detail: "Docs and files",
    icon: HardDrive,
    color: "text-orange-500",
    surface: "border-orange-500/20 bg-orange-500/5",
  },
  {
    id: "slack",
    composioSlug: "slack",
    name: "Slack",
    detail: "Team memory",
    icon: MessageSquare,
    color: "text-purple-500",
    surface: "border-purple-500/20 bg-purple-500/5",
  },
  {
    id: "notion",
    composioSlug: "notion",
    name: "Notion",
    detail: "Notes and pages",
    icon: FileText,
    color: "text-zinc-900 dark:text-zinc-100",
    surface: "border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50",
  },
  {
    id: "google-tasks",
    composioSlug: "googletasks",
    name: "Google Tasks",
    detail: "To-dos and lists",
    icon: CheckCircle2,
    color: "text-blue-500",
    surface: "border-blue-500/20 bg-blue-500/5",
  },
  {
    id: "x-twitter",
    composioSlug: "twitter",
    name: "X (Twitter)",
    detail: "Social context",
    icon: MessageSquare,
    color: "text-zinc-900 dark:text-zinc-100",
    surface: "border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50",
  },
  {
    id: "clickup",
    composioSlug: "clickup",
    name: "ClickUp",
    detail: "Project management",
    icon: CheckCircle2,
    color: "text-purple-500",
    surface: "border-purple-500/20 bg-purple-500/5",
  },
  {
    id: "cal-com",
    composioSlug: "calcom",
    name: "Cal.com",
    detail: "Scheduling",
    icon: CalendarDays,
    color: "text-zinc-900 dark:text-zinc-100",
    surface: "border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50",
  },
  {
    id: "google-docs",
    composioSlug: "googledocs",
    name: "Google Docs",
    detail: "Document context",
    icon: FileText,
    color: "text-blue-500",
    surface: "border-blue-500/20 bg-blue-500/5",
  },
  {
    id: "youtube",
    composioSlug: "youtube",
    name: "YouTube",
    detail: "Video content",
    icon: Images,
    color: "text-red-500",
    surface: "border-red-500/20 bg-red-500/5",
  },
];
