import {
  CalendarDays,
  FileText,
  HardDrive,
  Images,
  Mail,
  MessageSquare,
  CheckCircle2,
} from "lucide-react";

export const CONNECTORS = [
  {
    id: "google-calendar",
    composioSlug: "googlecalendar",
    name: "Google Calendar",
    detail: "View and manage your schedule.",
    icon: CalendarDays,
    color: "text-blue-500",
    tools: ["Read Events", "Create Meeting", "Check Availability"],
  },
  {
    id: "google-mail",
    composioSlug: "gmail",
    name: "Gmail",
    detail: "Search and read your emails.",
    icon: Mail,
    color: "text-red-500",
    tools: ["Search Inbox", "Summarize Threads", "Draft Reply"],
  },
  {
    id: "google-photos",
    composioSlug: "googlephotos",
    name: "Google Photos",
    detail: "Browse your photos and videos.",
    icon: Images,
    color: "text-emerald-500",
    tools: ["Fetch Photos", "Search by Date", "Get Media Info"],
  },
  {
    id: "google-drive",
    composioSlug: "googledrive",
    name: "Google Drive",
    detail: "Access and search your files.",
    icon: HardDrive,
    color: "text-orange-500",
    tools: ["List Files", "Download Content", "Search Folders"],
  },
  {
    id: "slack",
    composioSlug: "slack",
    name: "Slack",
    detail: "Read and search chat messages.",
    icon: MessageSquare,
    color: "text-purple-500",
    tools: ["Read Channels", "Search Messages", "Post Status"],
  },
  {
    id: "notion",
    composioSlug: "notion",
    name: "Notion",
    detail: "Access your notes and pages.",
    icon: FileText,
    color: "text-zinc-500",
    tools: ["List Pages", "Get Page Content", "Create Item"],
  },
  {
    id: "google-tasks",
    composioSlug: "googletasks",
    name: "Google Tasks",
    detail: "Manage your to-do lists.",
    icon: CheckCircle2,
    color: "text-blue-500",
    tools: ["List Tasks", "Complete Item", "Add New Task"],
  },
  {
    id: "youtube",
    composioSlug: "youtube",
    name: "YouTube",
    detail: "Search and watch videos.",
    icon: Images,
    color: "text-red-500",
    tools: ["Search Videos", "Get Channel Stats", "Fetch Captions"],
  },
];
